

echo "# Start Merge"

#python3 merge_generated_problems.py --output_format original generated_problems/analysis/output_original_caption_axiom_remapping/ generated_problems/analysis/output_original_sine_1_0
#python3 merge_generated_problems.py --output_format original generated_problems/analysis/output_original_caption_axiom_remapping/ generated_problems/analysis/output_original_sine_1_1


python3 merge_generated_problems.py --output_format original generated_problems/analysis/output_original_sine_1_1 generated_problems/analysis/output_original_caption_greedy_no_samples_4_length_22_conjecture_position_first_warmstart_output_original_unquoted_sine_1_1/
python3 merge_generated_problems.py --output_format original generated_problems/analysis/output_original_sine_1_1 generated_problems/analysis/output_original_caption_greedy_no_samples_4_length_22_axiom_remapping_conjecture_position_first_warmstart_output_original_unquoted_sine_1_1/



python3 merge_generated_problems.py --output_format original generated_problems/analysis/output_original_sine_2.5_2 generated_problems/analysis/output_original_caption_greedy_no_samples_4_length_22_conjecture_position_first_warmstart_output_original_unquoted_sine_1_1/
python3 merge_generated_problems.py --output_format original generated_problems/analysis/output_original_sine_2.5_2 generated_problems/analysis/output_original_caption_greedy_no_samples_4_length_22_axiom_remapping_conjecture_position_first_warmstart_output_original_unquoted_sine_1_1/



echo "# FINISHED #"
